from importlib import reload
import numpy as np
import matplotlib.pyplot as plt
import h5py, os, glob
import generator_object, to_generator_string, search, paths #these python classes should be in the same folder as cretin_main
for obj in [generator_object, to_generator_string, search, paths]:
    reload(obj)


# takes the text string and writes it too the creting generator file
def write(name : str, object):
    string = to_generator_string.Text_generator(object).execute()

    if not os.path.exists(paths.to_folder_test() + name):
        os.makedirs(paths.to_folder_test() + name)

    file_loc = paths.to_folder_test() + name + '/' + name + '.gen'
    print(f'writing too {file_loc}')
    with open(file_loc, 'w') as f:
        for x in string:
            f.write(str(x))

#  running cretin using the written generator file
def run(name):
    print(f'running cretin with {name}')
    import subprocess

    env = os.environ.copy()
    env["ARG_NAME0"] = name

    process = subprocess.Popen(paths.to_folder_cretin() + 'demo.sh', shell = True , stdout = subprocess.PIPE, stderr = subprocess.PIPE, env = env)
    process.wait() # Wait for process to complete.
    out, err = process.communicate()

    print(out.decode())
    print(err.decode())

# the data generated by cretin can be used for plots 
def plot(name):
    path_test = paths.to_folder_test()
    os.chdir(path_test + '/' + name)
    file_list = glob.glob('*.d*')
    fullpath = path_test + '/' + name + '/' + file_list[0]

    with h5py.File(fullpath, 'r') as f:
        path = path_test + name + '/images'
        if not os.path.exists(path):
            os.mkdir(path)
            
        print(f'plotting {name} too {path}')

        global arrays2d, arrays3d
        arrays2d, arrays3d = {}, {}
        counter = 0

        for key, value in f.items():
            arr = np.array(f[key])
            print(f'plot nr \t {counter} \t {key} \t {np.shape(arr)}')

            if len(arr.shape) == 2:
                plot3d(path, key, arr)

            if len(arr.shape) == 1 and len(arr) > 0:
                plot2d(path, key, arr)

            counter += 1

        print(f'plots {name} finished at location {path}')


def plot3d(path:str, masterkey:str, arr):
    print_bool = True
    for key, array in arrays3d.items():
        if np.shape(array) == np.shape(arr):
            if np.allclose(arr, array):
                print_bool = False
                print(f"{masterkey} is identical to other array")

    if print_bool:
        arrays3d[masterkey] = arr
        fig, ax = plt.subplots()
        im = ax.imshow(arr)
        ax.set_title(masterkey)

        fig.savefig(f'{path}/{masterkey}.png')
        fig.clf(); 
        plt.close()

def plot2d(path:str, masterkey:str, arr):
    print_bool = True
    for key, array in arrays2d.items():
        if np.shape(array) == np.shape(arr):
            if np.allclose(arr, array):
                print_bool = False
                print(f"{masterkey} is identical to other array")

    if print_bool:
        arrays2d[masterkey] = arr
        plt.plot(arr)
        plt.title(masterkey)
        plt.savefig(f'{path}/{masterkey}.png')
        plt.clf()
        plt.close()



def all(name: str, object):
    write(name, object)
    run(name)
    plot(name)

